/*
Single-Page RPG Generator by Tyler Robertson
For when you want to play Lasers & Feelings but don't want to play Lasers & Feelings
This page generates a random Lasers & Feelings hack for you by smashing a few nouns together.
Lasers & Feelings: http://onesevendesign.com/lasers_and_feelings_rpg.pdf
Words: https://github.com/dariusk/corpora/
*/

$("#generate").click(() => {
  generate();
});

const words = {
  "categories": [
    "Action & Adventure",
    "Action Comedy",
    "Action Sci-Fi & Fantasy",
    "Action Thriller",
    "Adult Animation",
    "Adventure",
    "African Movie",
    "Alien Sci-Fi",
    "Animal Tale",
    "Anime",
    "Anime Action",
    "Anime Comedy",
    "Anime Drama",
    "Anime Fantasy",
    "Anime Feature",
    "Anime Horror",
    "Anime Sci-Fi",
    "Anime Series",
    "Art House Movie",
    "Asian Action Movie",
    "Australian Movie",
    "B-Horror Movie",
    "Baseball Movie",
    "Basketball Movie",
    "Belgian Movie",
    "Biographical Documentary",
    "Biographical Drama",
    "Boxing Movie",
    "British Movie",
    "British TV Show",
    "Campy Movie",
    "Children & Family Movie",
    "Chinese Movie",
    "Classic Action & Adventure",
    "Classic Comedy",
    "Classic Drama",
    "Classic Foreign Movie",
    "Classic Movie",
    "Classic Musical",
    "Classic Romantic Movie",
    "Classic Sci-Fi & Fantasy",
    "Classic Thriller",
    "Classic TV Show",
    "Classic War Movie",
    "Classic Western",
    "Comedy",
    "Comic Book and Superhero Movie",
    "Country & Western/Folk",
    "Courtroom Drama",
    "Creature Feature",
    "Crime Action & Adventure",
    "Crime Documentary",
    "Crime Drama",
    "Crime Thriller",
    "Crime TV Show",
    "Cult Comedy",
    "Cult Horror Movie",
    "Cult Movie",
    "Cult Sci-Fi & Fantasy",
    "Cult TV Show",
    "Dark Comedy",
    "Deep Sea Horror Movie",
    "Disney",
    "Disney Musical",
    "Documentary",
    "Drama",
    "Drama based on Books",
    "Drama based on real life",
    "Dutch Movie",
    "Eastern European Movie",
    "Education for Kids",
    "Epic",
    "Experimental Movie",
    "Faith & Spirituality",
    "Faith & Spirituality Movie",
    "Family Feature",
    "Fantasy Movie",
    "Film Noir",
    "Food & Travel TV",
    "Football Movie",
    "Foreign Action & Adventure",
    "Foreign Comedy",
    "Foreign Documentary",
    "Foreign Drama",
    "Foreign Gay & Lesbian Movie",
    "Foreign Horror Movie",
    "Foreign Movie",
    "Foreign Sci-Fi & Fantasy",
    "Foreign Thriller",
    "French Movie",
    "Gangster Movie",
    "Gay & Lesbian Drama",
    "German Movie",
    "Greek Movie",
    "Historical Documentary",
    "Horror Comedy",
    "Horror Movie",
    "Independent Action & Adventure",
    "Independent Comedy",
    "Independent Drama",
    "Independent Movie",
    "Independent Thriller",
    "Indian Movie",
    "Irish Movie",
    "Italian Movie",
    "Japanese Movie",
    "Jazz & Easy Listening",
    "Kids Faith & Spirituality",
    "Kids Music",
    "Kids’ TV",
    "Korean Movie",
    "Korean TV Show",
    "Late Night Comedy",
    "Latin American Movie",
    "Latin Music",
    "Martial Arts Movie",
    "Martial Arts, Boxing & Wrestling",
    "Middle Eastern Movie",
    "Military Action & Adventure",
    "Military Documentary",
    "Military Drama",
    "Military TV Show",
    "Miniseries",
    "Mockumentary",
    "Monster Movie",
    "Movie based on children’s books",
    "Movie for ages 0 to 2",
    "Movie for ages 2 to 4",
    "Movie for ages 5 to 7",
    "Movie for ages 8 to 10",
    "Movie for ages 11 to 12",
    "Music & Concert Documentary",
    "Music",
    "Musical",
    "Mystery",
    "New Zealand Movie",
    "Period Piece",
    "Political Comedy",
    "Political Documentary",
    "Political Drama",
    "Political Thriller",
    "Psychological Thriller",
    "Quirky Romance",
    "Reality TV",
    "Religious Documentary",
    "Rock & Pop Concert",
    "Romantic Comedy",
    "Romantic Drama",
    "Romantic Favorite",
    "Romantic Foreign Movie",
    "Romantic Independent Movie",
    "Romantic Movie",
    "Russian",
    "Satanic Story",
    "Satire",
    "Scandinavian Movie",
    "Sci-Fi & Fantasy",
    "Sci-Fi Adventure",
    "Sci-Fi Drama",
    "Sci-Fi Horror Movie",
    "Sci-Fi Thriller",
    "Science & Nature Documentary",
    "Science & Nature TV",
    "Screwball Comedy",
    "Showbiz Drama",
    "Showbiz Musical",
    "Silent Movie",
    "Slapstick Comedy",
    "Slasher and Serial Killer Movie",
    "Soccer Movie",
    "Social & Cultural Documentary",
    "Social Issue Drama",
    "Southeast Asian Movie",
    "Spanish Movie",
    "Spiritual Documentary",
    "Sports & Fitness",
    "Sports Comedy",
    "Sports Documentary",
    "Sports Drama",
    "Sports Movie",
    "Spy Action & Adventure",
    "Spy Thriller",
    "Stage Musical",
    "Stand-up Comedy",
    "Steamy Romantic Movie",
    "Steamy Thriller",
    "Supernatural Horror Movie",
    "Supernatural Thriller",
    "Tearjerker",
    "Teen Comedy",
    "Teen Drama",
    "Teen Scream",
    "Teen TV Show",
    "Thriller",
    "Travel & Adventure Documentary",
    "TV Action & Adventure",
    "TV Cartoon",
    "TV Comedy",
    "TV Documentary",
    "TV Drama",
    "TV Horror",
    "TV Mystery",
    "TV Sci-Fi & Fantasy",
    "TV Show",
    "Urban & Dance Concert",
    "Vampire Horror Movie",
    "Werewolf Horror Movie",
    "Western",
    "World Music Concert",
    "Zombie Horror Movie"
  ],
  "occupations": [
		"accountant",
		"actor",
		"actuary",
		"adhesive bonding machine tender",
		"adjudicator",
		"administrative assistant",
		"administrative services manager",
		"adult education teacher",
		"advertising manager",
		"advertising sales agent",
		"aerobics instructor",
		"aerospace engineer",
		"aerospace engineering technician",
		"agent",
		"agricultural engineer",
		"agricultural equipment operator",
		"agricultural grader",
		"agricultural inspector",
		"agricultural manager",
		"agricultural sciences teacher",
		"agricultural sorter",
		"agricultural technician",
		"agricultural worker",
		"air conditioning installer",
		"air conditioning mechanic",
		"air traffic controller",
		"aircraft cargo handling supervisor",
		"aircraft mechanic",
		"aircraft service technician",
		"airline copilot",
		"airline pilot",
		"ambulance dispatcher",
		"ambulance driver",
		"amusement machine servicer",
		"anesthesiologist",
		"animal breeder",
		"animal control worker",
		"animal scientist",
		"animal trainer",
		"animator",
		"answering service operator",
		"anthropologist",
		"apparel patternmaker",
		"apparel worker",
		"arbitrator",
		"archeologist",
		"architect",
		"architectural drafter",
		"architectural manager",
		"archivist",
		"art director",
		"art teacher",
		"artist",
		"assembler",
		"astronomer",
		"athlete",
		"athletic trainer",
		"ATM machine repairer",
		"atmospheric scientist",
		"attendant",
		"audio and video equipment technician",
		"audio-visual and multimedia collections specialist",
		"audiologist",
		"auditor",
		"author",
		"auto damage insurance appraiser",
		"automotive and watercraft service attendant",
		"automotive glass installer",
		"automotive mechanic",
		"avionics technician",
		"baggage porter",
		"bailiff",
		"baker",
		"barback",
		"barber",
		"bartender",
		"basic education teacher",
		"behavioral disorder counselor",
		"bellhop",
		"bench carpenter",
		"bicycle repairer",
		"bill and account collector",
		"billing and posting clerk",
		"biochemist",
		"biological technician",
		"biomedical engineer",
		"biophysicist",
		"blaster",
		"blending machine operator",
		"blockmason",
		"boiler operator",
		"boilermaker",
		"bookkeeper",
		"boring machine tool tender",
		"brazer",
		"brickmason",
		"bridge and lock tender",
		"broadcast news analyst",
		"broadcast technician",
		"brokerage clerk",
		"budget analyst",
		"building inspector",
		"bus mechanic",
		"butcher",
		"buyer",
		"cabinetmaker",
		"cafeteria attendant",
		"cafeteria cook",
		"camera operator",
		"camera repairer",
		"cardiovascular technician",
		"cargo agent",
		"carpenter",
		"carpet installer",
		"cartographer",
		"cashier",
		"caster",
		"ceiling tile installer",
		"cellular equipment installer",
		"cement mason",
		"channeling machine operator",
		"chauffeur",
		"checker",
		"chef",
		"chemical engineer",
		"chemical plant operator",
		"chemist",
		"chemistry teacher",
		"chief executive",
		"child social worker",
		"childcare worker",
		"chiropractor",
		"choreographer",
		"civil drafter",
		"civil engineer",
		"civil engineering technician",
		"claims adjuster",
		"claims examiner",
		"claims investigator",
		"cleaner",
		"clinical laboratory technician",
		"clinical laboratory technologist",
		"clinical psychologist",
		"coating worker",
		"coatroom attendant",
		"coil finisher",
		"coil taper",
		"coil winder",
		"coin machine servicer",
		"commercial diver",
		"commercial pilot",
		"commodities sales agent",
		"communications equipment operator",
		"communications teacher",
		"community association manager",
		"community service manager",
		"compensation and benefits manager",
		"compliance officer",
		"composer",
		"computer hardware engineer",
		"computer network architect",
		"computer operator",
		"computer programmer",
		"computer science teacher",
		"computer support specialist",
		"computer systems administrator",
		"computer systems analyst",
		"concierge",
		"conciliator",
		"concrete finisher",
		"conservation science teacher",
		"conservation scientist",
		"conservation worker",
		"conservator",
		"construction inspector",
		"construction manager",
		"construction painter",
		"construction worker",
		"continuous mining machine operator",
		"convention planner",
		"conveyor operator",
		"cook",
		"cooling equipment operator",
		"copy marker",
		"correctional officer",
		"correctional treatment specialist",
		"correspondence clerk",
		"correspondent",
		"cosmetologist",
		"cost estimator",
		"costume attendant",
		"counseling psychologist",
		"counselor",
		"courier",
		"court reporter",
		"craft artist",
		"crane operator",
		"credit analyst",
		"credit checker",
		"credit counselor",
		"criminal investigator",
		"criminal justice teacher",
		"crossing guard",
		"curator",
		"custom sewer",
		"customer service representative",
		"cutter",
		"cutting machine operator",
		"dancer",
		"data entry keyer",
		"database administrator",
		"decorating worker",
		"delivery services driver",
		"demonstrator",
		"dental assistant",
		"dental hygienist",
		"dental laboratory technician",
		"dentist",
		"derrick operator",
		"designer",
		"desktop publisher",
		"detective",
		"diagnostic medical sonographer",
		"die maker",
		"diesel engine specialist",
		"dietetic technician",
		"dietitian",
		"dinkey operator",
		"director",
		"dishwasher",
		"dispatcher",
		"door-to-door sales worker",
		"drafter",
		"dragline operator",
		"drama teacher",
		"dredge operator",
		"dressing room attendant",
		"dressmaker",
		"drier operator",
		"drilling machine tool operator",
		"dry-cleaning worker",
		"drywall installer",
		"dyeing machine operator",
		"earth driller",
		"economics teacher",
		"economist",
		"editor",
		"education administrator",
		"electric motor repairer",
		"electrical electronics drafter",
		"electrical engineer",
		"electrical equipment assembler",
		"electrical installer",
		"electrical power-line installer",
		"electrician",
		"electro-mechanical technician",
		"elementary school teacher",
		"elevator installer",
		"elevator repairer",
		"embalmer",
		"emergency management director",
		"emergency medical technician",
		"engine assembler",
		"engineer",
		"engineering manager",
		"engineering teacher",
		"english language teacher",
		"engraver",
		"entertainment attendant",
		"environmental engineer",
		"environmental science teacher",
		"environmental scientist",
		"epidemiologist",
		"escort",
		"etcher",
		"event planner",
		"excavating operator",
		"executive administrative assistant",
		"executive secretary",
		"exhibit designer",
		"expediting clerk",
		"explosives worker",
		"extraction worker",
		"fabric mender",
		"fabric patternmaker",
		"fabricator",
		"faller",
		"family practitioner",
		"family social worker",
		"family therapist",
		"farm advisor",
		"farm equipment mechanic",
		"farm labor contractor",
		"farmer",
		"farmworker",
		"fashion designer",
		"fast food cook",
		"fence erector",
		"fiberglass fabricator",
		"fiberglass laminator",
		"file clerk",
		"filling machine operator",
		"film and video editor",
		"financial analyst",
		"financial examiner",
		"financial manager",
		"financial services sales agent",
		"fine artist",
		"fire alarm system installer",
		"fire dispatcher",
		"fire inspector",
		"fire investigator",
		"firefighter",
		"fish and game warden",
		"fish cutter",
		"fish trimmer",
		"fisher",
		"fitness studies teacher",
		"fitness trainer",
		"flight attendant",
		"floor finisher",
		"floor layer",
		"floor sander",
		"floral designer",
		"food batchmaker",
		"food cooking machine operator",
		"food preparation worker",
		"food science technician",
		"food scientist",
		"food server",
		"food service manager",
		"food technologist",
		"foreign language teacher",
		"foreign literature teacher",
		"forensic science technician",
		"forest fire inspector",
		"forest fire prevention specialist",
		"forest worker",
		"forester",
		"forestry teacher",
		"forging machine setter",
		"foundry coremaker",
		"freight agent",
		"freight mover",
		"fundraising manager",
		"funeral attendant",
		"funeral director",
		"funeral service manager",
		"furnace operator",
		"furnishings worker",
		"furniture finisher",
		"gaming booth cashier",
		"gaming cage worker",
		"gaming change person",
		"gaming dealer",
		"gaming investigator",
		"gaming manager",
		"gaming surveillance officer",
		"garment mender",
		"garment presser",
		"gas compressor",
		"gas plant operator",
		"gas pumping station operator",
		"general manager",
		"general practitioner",
		"geographer",
		"geography teacher",
		"geological engineer",
		"geological technician",
		"geoscientist",
		"glazier",
		"government program eligibility interviewer",
		"graduate teaching assistant",
		"graphic designer",
		"groundskeeper",
		"groundskeeping worker",
		"gynecologist",
		"hairdresser",
		"hairstylist",
		"hand grinding worker",
		"hand laborer",
		"hand packager",
		"hand packer",
		"hand polishing worker",
		"hand sewer",
		"hazardous materials removal worker",
		"head cook",
		"health and safety engineer",
		"health educator",
		"health information technician",
		"health services manager",
		"health specialties teacher",
		"healthcare social worker",
		"hearing officer",
		"heat treating equipment setter",
		"heating installer",
		"heating mechanic",
		"heavy truck driver",
		"highway maintenance worker",
		"historian",
		"history teacher",
		"hoist and winch operator",
		"home appliance repairer",
		"home economics teacher",
		"home entertainment installer",
		"home health aide",
		"home management advisor",
		"host",
		"hostess",
		"hostler",
		"hotel desk clerk",
		"housekeeping cleaner",
		"human resources assistant",
		"human resources manager",
		"human service assistant",
		"hunter",
		"hydrologist",
		"illustrator",
		"industrial designer",
		"industrial engineer",
		"industrial engineering technician",
		"industrial machinery mechanic",
		"industrial production manager",
		"industrial truck operator",
		"industrial-organizational psychologist",
		"information clerk",
		"information research scientist",
		"information security analyst",
		"information systems manager",
		"inspector",
		"instructional coordinator",
		"instructor",
		"insulation worker",
		"insurance claims clerk",
		"insurance sales agent",
		"insurance underwriter",
		"intercity bus driver",
		"interior designer",
		"internist",
		"interpreter",
		"interviewer",
		"investigator",
		"jailer",
		"janitor",
		"jeweler",
		"judge",
		"judicial law clerk",
		"kettle operator",
		"kiln operator",
		"kindergarten teacher",
		"laboratory animal caretaker",
		"landscape architect",
		"landscaping worker",
		"lathe setter",
		"laundry worker",
		"law enforcement teacher",
		"law teacher",
		"lawyer",
		"layout worker",
		"leather worker",
		"legal assistant",
		"legal secretary",
		"legislator",
		"librarian",
		"library assistant",
		"library science teacher",
		"library technician",
		"licensed practical nurse",
		"licensed vocational nurse",
		"life scientist",
		"lifeguard",
		"light truck driver",
		"line installer",
		"literacy teacher",
		"literature teacher",
		"loading machine operator",
		"loan clerk",
		"loan interviewer",
		"loan officer",
		"lobby attendant",
		"locker room attendant",
		"locksmith",
		"locomotive engineer",
		"locomotive firer",
		"lodging manager",
		"log grader",
		"logging equipment operator",
		"logistician",
		"machine feeder",
		"machinist",
		"magistrate judge",
		"magistrate",
		"maid",
		"mail clerk",
		"mail machine operator",
		"mail superintendent",
		"maintenance painter",
		"maintenance worker",
		"makeup artist",
		"management analyst",
		"manicurist",
		"manufactured building installer",
		"mapping technician",
		"marble setter",
		"marine engineer",
		"marine oiler",
		"market research analyst",
		"marketing manager",
		"marketing specialist",
		"marriage therapist",
		"massage therapist",
		"material mover",
		"materials engineer",
		"materials scientist",
		"mathematical science teacher",
		"mathematical technician",
		"mathematician",
		"maxillofacial surgeon",
		"measurer",
		"meat cutter",
		"meat packer",
		"meat trimmer",
		"mechanical door repairer",
		"mechanical drafter",
		"mechanical engineer",
		"mechanical engineering technician",
		"mediator",
		"medical appliance technician",
		"medical assistant",
		"medical equipment preparer",
		"medical equipment repairer",
		"medical laboratory technician",
		"medical laboratory technologist",
		"medical records technician",
		"medical scientist",
		"medical secretary",
		"medical services manager",
		"medical transcriptionist",
		"meeting planner",
		"mental health counselor",
		"mental health social worker",
		"merchandise displayer",
		"messenger",
		"metal caster",
		"metal patternmaker",
		"metal pickling operator",
		"metal pourer",
		"metal worker",
		"metal-refining furnace operator",
		"metal-refining furnace tender",
		"meter reader",
		"microbiologist",
		"middle school teacher",
		"milling machine setter",
		"millwright",
		"mine cutting machine operator",
		"mine shuttle car operator",
		"mining engineer",
		"mining safety engineer",
		"mining safety inspector",
		"mining service unit operator",
		"mixing machine setter",
		"mobile heavy equipment mechanic",
		"mobile home installer",
		"model maker",
		"model",
		"molder",
		"mortician",
		"motel desk clerk",
		"motion picture projectionist",
		"motorboat mechanic",
		"motorboat operator",
		"motorboat service technician",
		"motorcycle mechanic",
		"multimedia artist",
		"museum technician",
		"music director",
		"music teacher",
		"musical instrument repairer",
		"musician",
		"natural sciences manager",
		"naval architect",
		"network systems administrator",
		"new accounts clerk",
		"news vendor",
		"nonfarm animal caretaker",
		"nuclear engineer",
		"nuclear medicine technologist",
		"nuclear power reactor operator",
		"nuclear technician",
		"nursing aide",
		"nursing instructor",
		"nursing teacher",
		"nutritionist",
		"obstetrician",
		"occupational health and safety specialist",
		"occupational health and safety technician",
		"occupational therapist",
		"occupational therapy aide",
		"occupational therapy assistant",
		"offbearer",
		"office clerk",
		"office machine operator",
		"operating engineer",
		"operations manager",
		"operations research analyst",
		"ophthalmic laboratory technician",
		"optician",
		"optometrist",
		"oral surgeon",
		"order clerk",
		"order filler",
		"orderly",
		"ordnance handling expert",
		"orthodontist",
		"orthotist",
		"outdoor power equipment mechanic",
		"oven operator",
		"packaging machine operator",
		"painter ",
		"painting worker",
		"paper goods machine setter",
		"paperhanger",
		"paralegal",
		"paramedic",
		"parking enforcement worker",
		"parking lot attendant",
		"parts salesperson",
		"paving equipment operator",
		"payroll clerk",
		"pediatrician",
		"pedicurist",
		"personal care aide",
		"personal chef",
		"personal financial advisor",
		"pest control worker",
		"pesticide applicator",
		"pesticide handler",
		"pesticide sprayer",
		"petroleum engineer",
		"petroleum gauger",
		"petroleum pump system operator",
		"petroleum refinery operator",
		"petroleum technician",
		"pharmacist",
		"pharmacy aide",
		"pharmacy technician",
		"philosophy teacher",
		"photogrammetrist",
		"photographer",
		"photographic process worker",
		"photographic processing machine operator",
		"physical therapist aide",
		"physical therapist assistant",
		"physical therapist",
		"physician assistant",
		"physician",
		"physicist",
		"physics teacher",
		"pile-driver operator",
		"pipefitter",
		"pipelayer",
		"planing machine operator",
		"planning clerk",
		"plant operator",
		"plant scientist",
		"plasterer",
		"plastic patternmaker",
		"plastic worker",
		"plumber",
		"podiatrist",
		"police dispatcher",
		"police officer",
		"policy processing clerk",
		"political science teacher",
		"political scientist",
		"postal service clerk",
		"postal service mail carrier",
		"postal service mail processing machine operator",
		"postal service mail processor",
		"postal service mail sorter",
		"postmaster",
		"postsecondary teacher",
		"poultry cutter",
		"poultry trimmer",
		"power dispatcher",
		"power distributor",
		"power plant operator",
		"power tool repairer",
		"precious stone worker",
		"precision instrument repairer",
		"prepress technician",
		"preschool teacher",
		"priest",
		"print binding worker",
		"printing press operator",
		"private detective",
		"probation officer",
		"procurement clerk",
		"producer",
		"product promoter",
		"production clerk",
		"production occupation",
		"proofreader",
		"property manager",
		"prosthetist",
		"prosthodontist",
		"psychiatric aide",
		"psychiatric technician",
		"psychiatrist",
		"psychologist",
		"psychology teacher",
		"public relations manager",
		"public relations specialist",
		"pump operator",
		"purchasing agent",
		"purchasing manager",
		"radiation therapist",
		"radio announcer",
		"radio equipment installer",
		"radio operator",
		"radiologic technician",
		"radiologic technologist",
		"rail car repairer",
		"rail transportation worker",
		"rail yard engineer",
		"rail-track laying equipment operator",
		"railroad brake operator",
		"railroad conductor",
		"railroad police",
		"rancher",
		"real estate appraiser",
		"real estate broker",
		"real estate manager",
		"real estate sales agent",
		"receiving clerk",
		"receptionist",
		"record clerk",
		"recreation teacher",
		"recreation worker",
		"recreational therapist",
		"recreational vehicle service technician",
		"recyclable material collector",
		"referee",
		"refractory materials repairer",
		"refrigeration installer",
		"refrigeration mechanic",
		"refuse collector",
		"regional planner",
		"registered nurse",
		"rehabilitation counselor",
		"reinforcing iron worker",
		"reinforcing rebar worker",
		"religion teacher",
		"religious activities director",
		"religious worker",
		"rental clerk",
		"repair worker",
		"reporter",
		"residential advisor",
		"resort desk clerk",
		"respiratory therapist",
		"respiratory therapy technician",
		"retail buyer",
		"retail salesperson",
		"revenue agent",
		"rigger",
		"rock splitter",
		"rolling machine tender",
		"roof bolter",
		"roofer",
		"rotary drill operator",
		"roustabout",
		"safe repairer",
		"sailor",
		"sales engineer",
		"sales manager",
		"sales representative",
		"sampler",
		"sawing machine operator",
		"scaler",
		"school bus driver",
		"school psychologist",
		"school social worker",
		"scout leader",
		"sculptor",
		"secondary education teacher",
		"secondary school teacher",
		"secretary",
		"securities sales agent",
		"security guard",
		"security system installer",
		"segmental paver",
		"self-enrichment education teacher",
		"semiconductor processor",
		"septic tank servicer",
		"set designer",
		"sewer pipe cleaner",
		"sewing machine operator",
		"shampooer",
		"shaper",
		"sheet metal worker",
		"sheriff's patrol officer",
		"ship captain",
		"ship engineer",
		"ship loader",
		"shipmate",
		"shipping clerk",
		"shoe machine operator",
		"shoe worker",
		"short order cook",
		"signal operator",
		"signal repairer",
		"singer",
		"ski patrol",
		"skincare specialist",
		"slaughterer",
		"slicing machine tender",
		"slot supervisor",
		"social science research assistant",
		"social sciences teacher",
		"social scientist",
		"social service assistant",
		"social service manager",
		"social work teacher",
		"social worker",
		"sociologist",
		"sociology teacher",
		"software developer",
		"software engineer",
		"soil scientist",
		"solderer",
		"sorter",
		"sound engineering technician",
		"space scientist",
		"special education teacher",
		"speech-language pathologist",
		"sports book runner",
		"sports entertainer",
		"sports performer",
		"stationary engineer",
		"statistical assistant",
		"statistician",
		"steamfitter",
		"stock clerk",
		"stock mover",
		"stonemason",
		"street vendor",
		"streetcar operator",
		"structural iron worker",
		"structural metal fabricator",
		"structural metal fitter",
		"structural steel worker",
		"stucco mason",
		"substance abuse counselor",
		"substance abuse social worker",
		"subway operator",
		"surfacing equipment operator",
		"surgeon",
		"surgical technologist",
		"survey researcher",
		"surveying technician",
		"surveyor",
		"switch operator",
		"switchboard operator",
		"tailor",
		"tamping equipment operator",
		"tank car loader",
		"taper",
		"tax collector",
		"tax examiner",
		"tax preparer",
		"taxi driver",
		"teacher assistant",
		"teacher",
		"team assembler",
		"technical writer",
		"telecommunications equipment installer",
		"telemarketer",
		"telephone operator",
		"television announcer",
		"teller",
		"terrazzo finisher",
		"terrazzo worker",
		"tester",
		"textile bleaching operator",
		"textile cutting machine setter",
		"textile knitting machine setter",
		"textile presser",
		"textile worker",
		"therapist",
		"ticket agent",
		"ticket taker",
		"tile setter",
		"timekeeping clerk",
		"timing device assembler",
		"tire builder",
		"tire changer",
		"tire repairer",
		"title abstractor",
		"title examiner",
		"title searcher",
		"tobacco roasting machine operator",
		"tool filer",
		"tool grinder",
		"tool maker",
		"tool sharpener",
		"tour guide",
		"tower equipment installer",
		"tower operator",
		"track switch repairer",
		"tractor operator",
		"tractor-trailer truck driver",
		"traffic clerk",
		"traffic technician",
		"training and development manager",
		"training and development specialist",
		"transit police",
		"translator",
		"transportation equipment painter",
		"transportation inspector",
		"transportation security screener",
		"transportation worker",
		"trapper",
		"travel agent",
		"travel clerk",
		"travel guide",
		"tree pruner",
		"tree trimmer",
		"trimmer",
		"truck loader",
		"truck mechanic",
		"tuner",
		"turning machine tool operator",
		"typist",
		"umpire",
		"undertaker",
		"upholsterer",
		"urban planner",
		"usher",
		"valve installer",
		"vending machine servicer",
		"veterinarian",
		"veterinary assistant",
		"veterinary technician",
		"vocational counselor",
		"vocational education teacher",
		"waiter",
		"waitress",
		"watch repairer",
		"water treatment plant operator",
		"weaving machine setter",
		"web developer",
		"weigher",
		"welder",
		"wellhead pumper",
		"wholesale buyer",
		"wildlife biologist",
		"window trimmer",
		"wood patternmaker",
		"woodworker",
		"word processor",
		"writer",
		"yardmaster",
		"zoologist"
	],
  "adjs": [
    "Aristotelian",
    "Arthurian",
    "Bohemian",
    "Brethren",
    "Mosaic",
    "Oceanic",
    "Proctor",
    "Terran",
    "Tudor",
    "abroad",
    "absorbing",
    "abstract",
    "academic",
    "accelerated",
    "accented",
    "accountant",
    "acquainted",
    "acute",
    "addicting",
    "addictive",
    "adjustable",
    "admired",
    "adult",
    "adverse",
    "advised",
    "aerosol",
    "afraid",
    "aggravated",
    "aggressive",
    "agreeable",
    "alienate",
    "aligned",
    "all-round",
    "alleged",
    "almond",
    "alright",
    "altruistic",
    "ambient",
    "ambivalent",
    "amiable",
    "amino",
    "amorphous",
    "amused",
    "anatomical",
    "ancestral",
    "angelic",
    "angrier",
    "answerable",
    "antiquarian",
    "antiretroviral",
    "appellate",
    "applicable",
    "apportioned",
    "approachable",
    "appropriated",
    "archer",
    "aroused",
    "arrested",
    "assertive",
    "assigned",
    "athletic",
    "atrocious",
    "attained",
    "authoritarian",
    "autobiographical",
    "avaricious",
    "avocado",
    "awake",
    "awsome",
    "backstage",
    "backwoods",
    "balding",
    "bandaged",
    "banded",
    "banned",
    "barreled",
    "battle",
    "beaten",
    "begotten",
    "beguiled",
    "bellied",
    "belted",
    "beneficent",
    "besieged",
    "betting",
    "big-money",
    "biggest",
    "biochemical",
    "bipolar",
    "blackened",
    "blame",
    "blessed",
    "blindfolded",
    "bloat",
    "blocked",
    "blooded",
    "blue-collar",
    "blushing",
    "boastful",
    "bolder",
    "bolstered",
    "bonnie",
    "bored",
    "boundary",
    "bounded",
    "bounding",
    "branched",
    "brawling",
    "brazen",
    "breeding",
    "bridged",
    "brimming",
    "brimstone",
    "broadest",
    "broiled",
    "broker",
    "bronze",
    "bruising",
    "buffy",
    "bullied",
    "bungling",
    "burial",
    "buttery",
    "candied",
    "canonical",
    "cantankerous",
    "cardinal",
    "carefree",
    "caretaker",
    "casual",
    "cathartic",
    "causal",
    "chapel",
    "characterized",
    "charcoal",
    "cheeky",
    "cherished",
    "chipotle",
    "chirping",
    "chivalrous",
    "circumstantial",
    "civic",
    "civil",
    "civilised",
    "clanking",
    "clapping",
    "claptrap",
    "classless",
    "cleansed",
    "cleric",
    "cloistered",
    "codified",
    "colloquial",
    "colour",
    "combat",
    "combined",
    "comely",
    "commissioned",
    "commonplace",
    "commuter",
    "commuting",
    "comparable",
    "complementary",
    "compromising",
    "conceding",
    "concentrated",
    "conceptual",
    "conditioned",
    "confederate",
    "confident",
    "confidential",
    "confining",
    "confuse",
    "congressional",
    "consequential",
    "conservative",
    "constituent",
    "contaminated",
    "contemporaneous",
    "contraceptive",
    "convertible",
    "convex",
    "cooked",
    "coronary",
    "corporatist",
    "correlated",
    "corroborated",
    "cosmic",
    "cover",
    "crash",
    "crypto",
    "culminate",
    "cushioned",
    "dandy",
    "dashing",
    "dazzled",
    "decreased",
    "decrepit",
    "dedicated",
    "defaced",
    "defective",
    "defenseless",
    "deluded",
    "deodorant",
    "departed",
    "depress",
    "designing",
    "despairing",
    "destitute",
    "detective",
    "determined",
    "devastating",
    "deviant",
    "devilish",
    "devoted",
    "diagonal",
    "dictated",
    "didactic",
    "differentiated",
    "diffused",
    "dirtier",
    "disabling",
    "disconnected",
    "discovered",
    "disdainful",
    "diseased",
    "disfigured",
    "disheartened",
    "disheveled",
    "disillusioned",
    "disparate",
    "dissident",
    "doable",
    "doctrinal",
    "doing",
    "dotted",
    "double-blind",
    "downbeat",
    "dozen",
    "draining",
    "draught",
    "dread",
    "dried",
    "dropped",
    "dulled",
    "duplicate",
    "eaten",
    "echoing",
    "economical",
    "elaborated",
    "elastic",
    "elective",
    "electoral",
    "elven",
    "embryo",
    "emerald",
    "emergency",
    "emissary",
    "emotional",
    "employed",
    "enamel",
    "encased",
    "encrusted",
    "endangered",
    "engraved",
    "engrossing",
    "enlarged",
    "enlisted",
    "enlivened",
    "ensconced",
    "entangled",
    "enthralling",
    "entire",
    "envious",
    "eradicated",
    "eroded",
    "esoteric",
    "essential",
    "evaporated",
    "ever-present",
    "evergreen",
    "everlasting",
    "exacting",
    "exasperated",
    "excess",
    "exciting",
    "executable",
    "existent",
    "exonerated",
    "exorbitant",
    "exponential",
    "export",
    "extraordinary",
    "exultant",
    "exulting",
    "facsimile",
    "fading",
    "fainter",
    "faith-based",
    "fallacious",
    "faltering",
    "famous",
    "fancier",
    "fast-growing",
    "fated",
    "favourable",
    "fearless",
    "feathered",
    "fellow",
    "fermented",
    "ferocious",
    "fiddling",
    "filling",
    "firmer",
    "fitted",
    "flammable",
    "flawed",
    "fledgling",
    "fleshy",
    "flexible",
    "flickering",
    "floral",
    "flowering",
    "flowing",
    "foggy",
    "folic",
    "foolhardy",
    "foolish",
    "footy",
    "forehand",
    "forked",
    "formative",
    "formulaic",
    "foul-mouthed",
    "fractional",
    "fragrant",
    "fraudulent",
    "freakish",
    "freckled",
    "freelance",
    "freight",
    "fresh",
    "fretted",
    "frugal",
    "fulfilling",
    "fuming",
    "funded",
    "funny",
    "garbled",
    "gathered",
    "geologic",
    "geometric",
    "gibberish",
    "gilded",
    "ginger",
    "glare",
    "glaring",
    "gleaming",
    "glorified",
    "glorious",
    "goalless",
    "gold-plated",
    "goody",
    "grammatical",
    "grande",
    "grateful",
    "gratuitous",
    "graven",
    "greener",
    "grinding",
    "grizzly",
    "groaning",
    "grudging",
    "guaranteed",
    "gusty",
    "half-breed",
    "hand-held",
    "handheld",
    "hands-off",
    "hard-pressed",
    "harlot",
    "healing",
    "healthier",
    "healthiest",
    "heart",
    "heart-shaped",
    "heathen",
    "hedonistic",
    "heralded",
    "herbal",
    "high-density",
    "high-performance",
    "high-res",
    "high-yield",
    "hissy",
    "hitless",
    "holiness",
    "homesick",
    "honorable",
    "hooded",
    "hopeless",
    "horrendous",
    "horrible",
    "hot-button",
    "huddled",
    "human",
    "humbling",
    "humid",
    "humiliating",
    "hypnotized",
    "idealistic",
    "idiosyncratic",
    "ignited",
    "illustrated",
    "illustrative",
    "imitated",
    "immense",
    "immersive",
    "immigrant",
    "immoral",
    "impassive",
    "impressionable",
    "improbable",
    "impulsive",
    "in-between",
    "in-flight",
    "inattentive",
    "inbound",
    "inbounds",
    "incalculable",
    "incomprehensible",
    "indefatigable",
    "indigo",
    "indiscriminate",
    "indomitable",
    "inert",
    "inflate",
    "inform",
    "inheriting",
    "injured",
    "injurious",
    "inking",
    "inoffensive",
    "insane",
    "insensible",
    "insidious",
    "insincere",
    "insistent",
    "insolent",
    "insufferable",
    "intemperate",
    "interdependent",
    "interesting",
    "interfering",
    "intern",
    "interpreted",
    "intersecting",
    "intolerable",
    "intolerant",
    "intuitive",
    "irresolute",
    "irritate",
    "jealous",
    "jerking",
    "joining",
    "joint",
    "journalistic",
    "joyful",
    "keyed",
    "knowing",
    "lacklustre",
    "laden",
    "lagging",
    "lamented",
    "laughable",
    "layered",
    "leather",
    "leathern",
    "leery",
    "left-footed",
    "legible",
    "leisure",
    "lessening",
    "liberating",
    "life-size",
    "lifted",
    "lightest",
    "limitless",
    "listening",
    "literary",
    "liver",
    "livid",
    "lobster",
    "locked",
    "long-held",
    "long-lasting",
    "long-running",
    "long-suffering",
    "loudest",
    "loveliest",
    "low-budget",
    "low-carb",
    "lowering",
    "lucid",
    "luckless",
    "lusty",
    "luxurious",
    "magazine",
    "maniac",
    "manmade",
    "maroon",
    "mastered",
    "mated",
    "material",
    "materialistic",
    "meaningful",
    "measuring",
    "mediaeval",
    "medical",
    "meditated",
    "medley",
    "melodic",
    "memorable",
    "memorial",
    "metabolic",
    "metallic",
    "metallurgical",
    "metering",
    "midair",
    "midterm",
    "midway",
    "mighty",
    "migrating",
    "mind-blowing",
    "mind-boggling",
    "minor",
    "mirrored",
    "misguided",
    "misshapen",
    "mitigated",
    "mixed",
    "modernized",
    "molecular",
    "monarch",
    "monastic",
    "morbid",
    "motley",
    "motorized",
    "mounted",
    "multi-million",
    "multidisciplinary",
    "muscled",
    "muscular",
    "muted",
    "mysterious",
    "mythic",
    "nail-biting",
    "natural",
    "nauseous",
    "negative",
    "networked",
    "neurological",
    "neutered",
    "newest",
    "night",
    "nitrous",
    "no-fly",
    "noncommercial",
    "nonsense",
    "north",
    "nuanced",
    "occurring",
    "offensive",
    "oldest",
    "oncoming",
    "one-eyed",
    "one-year",
    "onstage",
    "onward",
    "opaque",
    "open-ended",
    "operating",
    "opportunist",
    "opposing",
    "opt-in",
    "ordinate",
    "outdone",
    "outlaw",
    "outsized",
    "overboard",
    "overheated",
    "oversize",
    "overworked",
    "oyster",
    "paced",
    "panting",
    "paralyzed",
    "paramount",
    "parental",
    "parted",
    "partisan",
    "passive",
    "pastel",
    "patriot",
    "peacekeeping",
    "pedestrian",
    "peevish",
    "penal",
    "penned",
    "pensive",
    "perceptual",
    "perky",
    "permissible",
    "pernicious",
    "perpetuate",
    "perplexed",
    "pervasive",
    "petrochemical",
    "philosophical",
    "picturesque",
    "pillaged",
    "piped",
    "piquant",
    "pitching",
    "plausible",
    "pliable",
    "plumb",
    "politician",
    "polygamous",
    "poorest",
    "portmanteau",
    "posed",
    "positive",
    "possible",
    "postpartum",
    "prank",
    "pre-emptive",
    "precocious",
    "predicted",
    "premium",
    "preparatory",
    "prerequisite",
    "prescient",
    "preserved",
    "presidential",
    "pressed",
    "pressurized",
    "presumed",
    "prewar",
    "priced",
    "pricier",
    "primal",
    "primer",
    "primetime",
    "printed",
    "private",
    "problem",
    "procedural",
    "process",
    "prodigious",
    "professional",
    "programmed",
    "progressive",
    "prolific",
    "promising",
    "promulgated",
    "pronged",
    "proportionate",
    "protracted",
    "pulled",
    "pulsed",
    "purgatory",
    "quick",
    "rapid-fire",
    "raunchy",
    "razed",
    "reactive",
    "readable",
    "realizing",
    "recognised",
    "recovering",
    "recurrent",
    "recycled",
    "redeemable",
    "reflecting",
    "regal",
    "registering",
    "reliable",
    "reminiscent",
    "remorseless",
    "removable",
    "renewable",
    "repeating",
    "repellent",
    "reserve",
    "resigned",
    "respectful",
    "rested",
    "restrict",
    "resultant",
    "retaliatory",
    "retiring",
    "revelatory",
    "reverend",
    "reversing",
    "revolving",
    "ridiculous",
    "right-hand",
    "ringed",
    "risque",
    "robust",
    "roomful",
    "rotating",
    "roused",
    "rubber",
    "run-down",
    "running",
    "runtime",
    "rustling",
    "safest",
    "salient",
    "sanctioned",
    "saute",
    "saved",
    "scandalized",
    "scarlet",
    "scattering",
    "sceptical",
    "scheming",
    "scoundrel",
    "scratched",
    "scratchy",
    "scrolled",
    "seated",
    "second-best",
    "segregated",
    "self-taught",
    "semiautomatic",
    "senior",
    "sensed",
    "sentient",
    "sexier",
    "shadowy",
    "shaken",
    "shaker",
    "shameless",
    "shaped",
    "shiny",
    "shipped",
    "shivering",
    "shoestring",
    "short",
    "short-lived",
    "signed",
    "simplest",
    "simplistic",
    "sizable",
    "skeleton",
    "skinny",
    "skirting",
    "skyrocketed",
    "slamming",
    "slanting",
    "slapstick",
    "sleek",
    "sleepless",
    "sleepy",
    "slender",
    "slimmer",
    "smacking",
    "smokeless",
    "smothered",
    "smouldering",
    "snuff",
    "socialized",
    "solid-state",
    "sometime",
    "sought",
    "spanking",
    "sparing",
    "spattered",
    "specialized",
    "specific",
    "speedy",
    "spherical",
    "spiky",
    "spineless",
    "sprung",
    "squint",
    "stainless",
    "standing",
    "starlight",
    "startled",
    "stately",
    "statewide",
    "stereoscopic",
    "sticky",
    "stimulant",
    "stinky",
    "stoked",
    "stolen",
    "storied",
    "strained",
    "strapping",
    "strengthened",
    "stubborn",
    "stylized",
    "suave",
    "subjective",
    "subjugated",
    "subordinate",
    "succeeding",
    "suffering",
    "summary",
    "sunset",
    "sunshine",
    "supernatural",
    "supervisory",
    "supply-side",
    "surrogate",
    "suspended",
    "suspenseful",
    "swarthy",
    "sweating",
    "sweeping",
    "swinging",
    "swooning",
    "sympathize",
    "synchronized",
    "synonymous",
    "synthetic",
    "tailed",
    "tallest",
    "tangible",
    "tanked",
    "tarry",
    "technical",
    "tectonic",
    "telepathic",
    "tenderest",
    "territorial",
    "testimonial",
    "theistic",
    "thicker",
    "threatening",
    "tight-lipped",
    "timed",
    "timely",
    "timid",
    "torrent",
    "totalled",
    "tougher",
    "traditional",
    "transformed",
    "trapped",
    "traveled",
    "traverse",
    "treated",
    "trial",
    "trunk",
    "trusting",
    "trying",
    "twisted",
    "two-lane",
    "tyrannical",
    "unaided",
    "unassisted",
    "unassuming",
    "unattractive",
    "uncapped",
    "uncomfortable",
    "uncontrolled",
    "uncooked",
    "uncooperative",
    "underground",
    "undersea",
    "undisturbed",
    "unearthly",
    "uneasy",
    "unequal",
    "unfazed",
    "unfinished",
    "unforeseen",
    "unforgivable",
    "unidentified",
    "unimaginative",
    "uninspired",
    "unintended",
    "uninvited",
    "universal",
    "unmasked",
    "unorthodox",
    "unparalleled",
    "unpleasant",
    "unprincipled",
    "unread",
    "unreasonable",
    "unregulated",
    "unreliable",
    "unremitting",
    "unsafe",
    "unsanitary",
    "unsealed",
    "unsuccessful",
    "unsupervised",
    "untimely",
    "unwary",
    "unwrapped",
    "uppity",
    "upstart",
    "useless",
    "utter",
    "valiant",
    "valid",
    "valued",
    "vanilla",
    "vaulting",
    "vaunted",
    "veering",
    "vegetative",
    "vented",
    "verbal",
    "verifying",
    "veritable",
    "versed",
    "vinyl",
    "virgin",
    "visceral",
    "visual",
    "voluptuous",
    "walk-on",
    "wanton",
    "warlike",
    "washed",
    "waterproof",
    "waved",
    "weakest",
    "well-bred",
    "well-chosen",
    "well-informed",
    "wetting",
    "wheeled",
    "whirlwind",
    "widen",
    "widening",
    "willful",
    "willing",
    "winnable",
    "winningest",
    "wireless",
    "wistful",
    "woeful",
    "wooded",
    "woodland",
    "wordless",
    "workable",
    "worldly",
    "worldwide",
    "worst-case",
    "worsted",
    "worthless"],
  "nouns": [
    "Armour",
    "Barrymore",
    "Cabot",
    "Catholicism",
    "Chihuahua",
    "Christianity",
    "Easter",
    "Frenchman",
    "Lowry",
    "Mayer",
    "Orientalism",
    "Pharaoh",
    "Pueblo",
    "Pullman",
    "Rodeo",
    "Saturday",
    "Sister",
    "Snead",
    "Syrah",
    "Tuesday",
    "Woodward",
    "abbey",
    "absence",
    "absorption",
    "abstinence",
    "absurdity",
    "abundance",
    "acceptance",
    "accessibility",
    "accommodation",
    "accomplice",
    "accountability",
    "accounting",
    "accreditation",
    "accuracy",
    "acquiescence",
    "acreage",
    "actress",
    "actuality",
    "adage",
    "adaptation",
    "adherence",
    "adjustment",
    "adoption",
    "adultery",
    "advancement",
    "advert",
    "advertisement",
    "advertising",
    "advice",
    "aesthetics",
    "affinity",
    "aggression",
    "agriculture",
    "aircraft",
    "airtime",
    "allegation",
    "allegiance",
    "allegory",
    "allergy",
    "allies",
    "alligator",
    "allocation",
    "allotment",
    "altercation",
    "ambulance",
    "ammonia",
    "anatomy",
    "anemia",
    "ankle",
    "announcement",
    "annoyance",
    "annuity",
    "anomaly",
    "anthropology",
    "anxiety",
    "apartheid",
    "apologise",
    "apostle",
    "apparatus",
    "appeasement",
    "appellation",
    "appendix",
    "applause",
    "appointment",
    "appraisal",
    "archery",
    "archipelago",
    "architecture",
    "ardor",
    "arrears",
    "arrow",
    "artisan",
    "artistry",
    "ascent",
    "assembly",
    "assignment",
    "association",
    "asthma",
    "atheism",
    "attacker",
    "attraction",
    "attractiveness",
    "auspices",
    "authority",
    "avarice",
    "aversion",
    "aviation",
    "babbling",
    "backlash",
    "baker",
    "ballet",
    "balls",
    "banjo",
    "baron",
    "barrier",
    "barrister",
    "bases",
    "basin",
    "basis",
    "battery",
    "battling",
    "bedtime",
    "beginner",
    "begun",
    "bending",
    "bicycle",
    "billing",
    "bingo",
    "biography",
    "biology",
    "birthplace",
    "blackberry",
    "blather",
    "blossom",
    "boardroom",
    "boasting",
    "bodyguard",
    "boldness",
    "bomber",
    "bondage",
    "bonding",
    "bones",
    "bonus",
    "bookmark",
    "boomer",
    "booty",
    "bounds",
    "bowling",
    "brainstorming",
    "breadth",
    "breaker",
    "brewer",
    "brightness",
    "broccoli",
    "broth",
    "brotherhood",
    "browsing",
    "brunch",
    "brunt",
    "building",
    "bullion",
    "bureaucracy",
    "burglary",
    "buyout",
    "by-election",
    "cabal",
    "cabbage",
    "calamity",
    "campaign",
    "canonization",
    "captaincy",
    "carcass",
    "carrier",
    "cartridge",
    "cassette",
    "catfish",
    "caught",
    "celebrity",
    "cemetery",
    "certainty",
    "certification",
    "charade",
    "chasm",
    "check-in",
    "cheerleader",
    "cheesecake",
    "chemotherapy",
    "chili",
    "china",
    "chivalry",
    "cholera",
    "cilantro",
    "circus",
    "civilisation",
    "civility",
    "clearance",
    "clearing",
    "clerk",
    "climber",
    "closeness",
    "clothing",
    "clutches",
    "coaster",
    "coconut",
    "coding",
    "collaborator",
    "colleague",
    "college",
    "collision",
    "colors",
    "combustion",
    "comedian",
    "comer",
    "commander",
    "commemoration",
    "commenter",
    "commissioner",
    "commune",
    "competition",
    "completeness",
    "complexity",
    "computing",
    "comrade",
    "concur",
    "condominium",
    "conduit",
    "confidant",
    "configuration",
    "confiscation",
    "conflagration",
    "conflict",
    "consist",
    "consistency",
    "consolidation",
    "conspiracy",
    "constable",
    "consul",
    "consultancy",
    "contentment",
    "contents",
    "contractor",
    "conversation",
    "cornerstone",
    "corpus",
    "correlation",
    "councilman",
    "counselor",
    "countdown",
    "countryman",
    "coverage",
    "covering",
    "coyote",
    "cracker",
    "creator",
    "criminality",
    "crocodile",
    "cropping",
    "cross-examination",
    "crossover",
    "crossroads",
    "culprit",
    "cumin",
    "curator",
    "curfew",
    "cursor",
    "custard",
    "cutter",
    "cyclist",
    "cyclone",
    "cylinder",
    "cynicism",
    "daddy",
    "damsel",
    "darkness",
    "dawning",
    "daybreak",
    "dealing",
    "dedication",
    "deduction",
    "defection",
    "deference",
    "deficiency",
    "definition",
    "deflation",
    "degeneration",
    "delegation",
    "delicacy",
    "delirium",
    "deliverance",
    "demeanor",
    "demon",
    "demonstration",
    "denomination",
    "dentist",
    "departure",
    "depletion",
    "depression",
    "designation",
    "despotism",
    "detention",
    "developer",
    "devolution",
    "dexterity",
    "diagnosis",
    "dialect",
    "differentiation",
    "digger",
    "digress",
    "dioxide",
    "diploma",
    "disability",
    "disarmament",
    "discord",
    "discovery",
    "dishonesty",
    "dismissal",
    "disobedience",
    "dispatcher",
    "disservice",
    "distribution",
    "distributor",
    "diver",
    "diversity",
    "docking",
    "dollar",
    "dominance",
    "domination",
    "dominion",
    "donkey",
    "doorstep",
    "doorway",
    "dossier",
    "downside",
    "drafting",
    "drank",
    "drilling",
    "driver",
    "drumming",
    "drunkenness",
    "duchess",
    "ducking",
    "dugout",
    "dumps",
    "dwelling",
    "dynamics",
    "eagerness",
    "earnestness",
    "earnings",
    "eater",
    "editor",
    "effectiveness",
    "electricity",
    "elements",
    "eloquence",
    "emancipation",
    "embodiment",
    "embroidery",
    "emperor",
    "employment",
    "encampment",
    "enclosure",
    "encouragement",
    "endangerment",
    "enlightenment",
    "enthusiasm",
    "environment",
    "environs",
    "envoy",
    "epilepsy",
    "equation",
    "equator",
    "error",
    "espionage",
    "estimation",
    "evacuation",
    "exaggeration",
    "examination",
    "exclamation",
    "expediency",
    "exploitation",
    "extinction",
    "eyewitness",
    "falls",
    "fascism",
    "fastball",
    "feces",
    "feedback",
    "ferocity",
    "fertilization",
    "fetish",
    "finale",
    "firing",
    "fixing",
    "flashing",
    "flask",
    "flora",
    "fluke",
    "folklore",
    "follower",
    "foothold",
    "footing",
    "forefinger",
    "forefront",
    "forgiveness",
    "formality",
    "formation",
    "formula",
    "foyer",
    "fragmentation",
    "framework",
    "fraud",
    "freestyle",
    "frequency",
    "friendliness",
    "fries",
    "frigate",
    "fulfillment",
    "function",
    "functionality",
    "fundraiser",
    "fusion",
    "futility",
    "gallantry",
    "gallery",
    "genesis",
    "genitals",
    "girlfriend",
    "glamour",
    "glitter",
    "glucose",
    "google",
    "grandeur",
    "grappling",
    "greens",
    "gridlock",
    "grocer",
    "groundwork",
    "grouping",
    "gunman",
    "gusto",
    "habitation",
    "hacker",
    "hallway",
    "hamburger",
    "hammock",
    "handling",
    "hands",
    "handshake",
    "happiness",
    "hardship",
    "headcount",
    "header",
    "headquarters",
    "heads",
    "headset",
    "hearth",
    "hearts",
    "heath",
    "hegemony",
    "height",
    "hello",
    "helper",
    "helping",
    "helplessness",
    "hierarchy",
    "hoarding",
    "hockey",
    "homeland",
    "homer",
    "honesty",
    "horror",
    "horseman",
    "hostility",
    "housing",
    "humility",
    "hurricane",
    "iceberg",
    "ignition",
    "illness",
    "illustration",
    "illustrator",
    "immunity",
    "immunization",
    "imperialism",
    "imprisonment",
    "inaccuracy",
    "inaction",
    "inactivity",
    "inauguration",
    "indecency",
    "indicator",
    "inevitability",
    "infamy",
    "infiltration",
    "influx",
    "iniquity",
    "innocence",
    "innovation",
    "insanity",
    "inspiration",
    "instruction",
    "instructor",
    "insurer",
    "interact",
    "intercession",
    "intercourse",
    "intermission",
    "interpretation",
    "intersection",
    "interval",
    "intolerance",
    "intruder",
    "invasion",
    "investment",
    "involvement",
    "irrigation",
    "iteration",
    "jenny",
    "jogging",
    "jones",
    "joseph",
    "juggernaut",
    "juncture",
    "jurisprudence",
    "juror",
    "kangaroo",
    "kingdom",
    "knocking",
    "laborer",
    "larceny",
    "laurels",
    "layout",
    "leadership",
    "leasing",
    "legislation",
    "leopard",
    "liberation",
    "licence",
    "lifeblood",
    "lifeline",
    "ligament",
    "lighting",
    "likeness",
    "line-up",
    "lineage",
    "liner",
    "lineup",
    "liquidation",
    "listener",
    "literature",
    "litigation",
    "litre",
    "loathing",
    "locality",
    "lodging",
    "logic",
    "longevity",
    "lookout",
    "lordship",
    "lustre",
    "ma'am",
    "machinery",
    "madness",
    "magnificence",
    "mahogany",
    "mailing",
    "mainframe",
    "maintenance",
    "majority",
    "manga",
    "mango",
    "manifesto",
    "mantra",
    "manufacturer",
    "maple",
    "martin",
    "martyrdom",
    "mathematician",
    "matrix",
    "matron",
    "mayhem",
    "mayor",
    "means",
    "meantime",
    "measurement",
    "mechanics",
    "mediator",
    "medics",
    "melodrama",
    "memory",
    "mentality",
    "metaphysics",
    "method",
    "metre",
    "miner",
    "mirth",
    "misconception",
    "misery",
    "mishap",
    "misunderstanding",
    "mobility",
    "molasses",
    "momentum",
    "monarchy",
    "monument",
    "morale",
    "mortality",
    "motto",
    "mouthful",
    "mouthpiece",
    "mover",
    "movie",
    "mowing",
    "murderer",
    "musician",
    "mutation",
    "mythology",
    "narration",
    "narrator",
    "nationality",
    "negligence",
    "neighborhood",
    "neighbour",
    "nervousness",
    "networking",
    "nexus",
    "nightmare",
    "nobility",
    "nobody",
    "noodle",
    "normalcy",
    "notification",
    "nourishment",
    "novella",
    "nucleus",
    "nuisance",
    "nursery",
    "nutrition",
    "nylon",
    "oasis",
    "obscenity",
    "obscurity",
    "observer",
    "offense",
    "onslaught",
    "operation",
    "opportunity",
    "opposition",
    "oracle",
    "orchestra",
    "organisation",
    "organizer",
    "orientation",
    "originality",
    "ounce",
    "outage",
    "outcome",
    "outdoors",
    "outfield",
    "outing",
    "outpost",
    "outset",
    "overseer",
    "owner",
    "oxygen",
    "pairing",
    "panther",
    "paradox",
    "parliament",
    "parsley",
    "parson",
    "passenger",
    "pasta",
    "patchwork",
    "pathos",
    "patriotism",
    "pendulum",
    "penguin",
    "permission",
    "persona",
    "perusal",
    "pessimism",
    "peter",
    "philosopher",
    "phosphorus",
    "phrasing",
    "physique",
    "piles",
    "plateau",
    "playing",
    "plaza",
    "plethora",
    "plurality",
    "pneumonia",
    "pointer",
    "poker",
    "policeman",
    "polling",
    "poster",
    "posterity",
    "posting",
    "postponement",
    "potassium",
    "pottery",
    "poultry",
    "pounding",
    "pragmatism",
    "precedence",
    "precinct",
    "preoccupation",
    "pretense",
    "priesthood",
    "prisoner",
    "privacy",
    "probation",
    "proceeding",
    "proceedings",
    "processing",
    "processor",
    "progression",
    "projection",
    "prominence",
    "propensity",
    "prophecy",
    "prorogation",
    "prospectus",
    "protein",
    "prototype",
    "providence",
    "provider",
    "provocation",
    "proximity",
    "puberty",
    "publicist",
    "publicity",
    "publisher",
    "pundit",
    "putting",
    "quantity",
    "quart",
    "quilting",
    "quorum",
    "racism",
    "radiance",
    "ralph",
    "rancher",
    "ranger",
    "rapidity",
    "rapport",
    "ratification",
    "rationality",
    "reaction",
    "reader",
    "reassurance",
    "rebirth",
    "receptor",
    "recipe",
    "recognition",
    "recourse",
    "recreation",
    "rector",
    "recurrence",
    "redemption",
    "redistribution",
    "redundancy",
    "refinery",
    "reformer",
    "refrigerator",
    "regularity",
    "regulator",
    "reinforcement",
    "reins",
    "reinstatement",
    "relativism",
    "relaxation",
    "rendition",
    "repayment",
    "repentance",
    "repertoire",
    "repository",
    "republic",
    "reputation",
    "resentment",
    "residency",
    "resignation",
    "restaurant",
    "resurgence",
    "retailer",
    "retention",
    "retirement",
    "reviewer",
    "riches",
    "righteousness",
    "roadblock",
    "robber",
    "rocks",
    "rubbing",
    "runoff",
    "saloon",
    "salvation",
    "sarcasm",
    "saucer",
    "savior",
    "scarcity",
    "scenario",
    "scenery",
    "schism",
    "scholarship",
    "schoolboy",
    "schooner",
    "scissors",
    "scolding",
    "scooter",
    "scouring",
    "scrimmage",
    "scrum",
    "seating",
    "sediment",
    "seduction",
    "seeder",
    "seizure",
    "self-confidence",
    "self-control",
    "self-respect",
    "semicolon",
    "semiconductor",
    "semifinal",
    "senator",
    "sending",
    "serenity",
    "seriousness",
    "servitude",
    "sesame",
    "setup",
    "sewing",
    "sharpness",
    "shaving",
    "shoplifting",
    "shopping",
    "siding",
    "simplicity",
    "simulation",
    "sinking",
    "skate",
    "sloth",
    "slugger",
    "snack",
    "snail",
    "snapshot",
    "snark",
    "soccer",
    "solemnity",
    "solicitation",
    "solitude",
    "somewhere",
    "sophistication",
    "sorcery",
    "souvenir",
    "spaghetti",
    "specification",
    "specimen",
    "specs",
    "spectacle",
    "spectre",
    "speculation",
    "sperm",
    "spoiler",
    "squad",
    "squid",
    "staging",
    "stagnation",
    "staircase",
    "stairway",
    "stamina",
    "standpoint",
    "standstill",
    "stanza",
    "statement",
    "stillness",
    "stimulus",
    "stocks",
    "stole",
    "stoppage",
    "storey",
    "storyteller",
    "stylus",
    "subcommittee",
    "subscription",
    "subsidy",
    "suburb",
    "success",
    "sufferer",
    "supposition",
    "suspension",
    "sweater",
    "sweepstakes",
    "swimmer",
    "syndrome",
    "synopsis",
    "syntax",
    "system",
    "tablespoon",
    "taker",
    "tavern",
    "technology",
    "telephony",
    "template",
    "tempo",
    "tendency",
    "tendon",
    "terrier",
    "terror",
    "terry",
    "theater",
    "theology",
    "therapy",
    "thicket",
    "thoroughfare",
    "threshold",
    "thriller",
    "thunderstorm",
    "ticker",
    "tiger",
    "tights",
    "to-day",
    "tossing",
    "touchdown",
    "tourist",
    "tourney",
    "toxicity",
    "tracing",
    "tractor",
    "translation",
    "transmission",
    "transmitter",
    "trauma",
    "traveler",
    "treadmill",
    "trilogy",
    "trout",
    "tuning",
    "twenties",
    "tycoon",
    "tyrant",
    "ultimatum",
    "underdog",
    "underwear",
    "unhappiness",
    "unification",
    "university",
    "uprising",
    "vaccination",
    "validity",
    "vampire",
    "vanguard",
    "variation",
    "vegetation",
    "verification",
    "viability",
    "vicinity",
    "victory",
    "viewpoint",
    "villa",
    "vindication",
    "violation",
    "vista",
    "vocalist",
    "vogue",
    "volcano",
    "voltage",
    "vomiting",
    "vulnerability",
    "waistcoat",
    "waitress",
    "wardrobe",
    "warmth",
    "watchdog",
    "wealth",
    "weariness",
    "whereabouts",
    "whisky",
    "whiteness",
    "widget",
    "width",
    "windfall",
    "wiring",
    "witchcraft",
    "withholding",
    "womanhood",
    "words",
    "workman",
    "youngster" ],
  "objects": [
    "ball gown",
    "belt",
    "bikini",
    "blazer",
    "blouse",
    "boot",
    "bow tie",
    "bra",
    "bra & knicker set",
    "camisole",
    "cap",
    "cardigan",
    "catsuit",
    "chemise",
    "coat",
    "corset",
    "cravat",
    "cummerbund",
    "dinner jacket",
    "dress",
    "dressing gown",
    "fleece",
    "glove",
    "hat",
    "hoody",
    "jacket",
    "jogging suit",
    "jumper",
    "kaftan",
    "kilt",
    "kurta",
    "lingerie",
    "nightgown",
    "nightwear",
    "pashmina",
    "polo shirt",
    "poncho",
    "raincoat",
    "robe",
    "romper",
    "sarong",
    "scarf",
    "shawl",
    "shellsuit",
    "shirt",
    "skirt",
    "suit",
    "sweater",
    "sweatshirt",
    "swimming costume",
    "swimwear",
    "t-shirt",
    "tailcoat",
    "tankini",
    "thong",
    "tie",
    "tracksuit",
    "undershirt",
    "vest",
    "waistcoat",
    "CD",
    "Christmas ornament",
    "acorn",
    "apple",
    "bag",
    "bag of cotton balls",
    "bag of popcorn",
    "bag of rubber bands",
    "ball of yarn",
    "balloon",
    "banana",
    "bananas",
    "bandana",
    "bangle bracelet",
    "bar of soap",
    "baseball",
    "baseball bat",
    "baseball hat",
    "basketball",
    "beaded bracelet",
    "beaded necklace",
    "bed",
    "beef",
    "bell",
    "belt",
    "blouse",
    "blowdryer",
    "bonesaw",
    "book",
    "book of jokes",
    "book of matches",
    "bookmark",
    "boom box",
    "bottle",
    "bottle cap",
    "bottle of glue",
    "bottle of honey",
    "bottle of ink",
    "bottle of lotion",
    "bottle of nail polish",
    "bottle of oil",
    "bottle of paint",
    "bottle of perfume",
    "bottle of pills",
    "bottle of soda",
    "bottle of sunscreen",
    "bottle of syrup",
    "bottle of water",
    "bouquet of flowers",
    "bow",
    "bow tie",
    "bowl",
    "box",
    "box of Q-tips",
    "box of baking soda",
    "box of chalk",
    "box of chocolates",
    "box of crayons",
    "box of markers",
    "box of tissues",
    "bracelet",
    "bread",
    "broccoli",
    "brush",
    "buckle",
    "butter knife",
    "button",
    "camera",
    "can of beans",
    "can of chili",
    "can of peas",
    "can of whipped cream",
    "candle",
    "candlestick",
    "candy bar",
    "candy cane",
    "candy wrapper",
    "canteen",
    "canvas",
    "car",
    "card",
    "carrot",
    "carrots",
    "cars",
    "carton of ice cream",
    "cat",
    "catalogue",
    "cell phone",
    "cellphone",
    "cement stone",
    "chain",
    "chair",
    "chalk",
    "chapter book",
    "check book",
    "chenille stick",
    "chicken",
    "children's book",
    "chocolate",
    "class ring",
    "clay pot",
    "clock",
    "clothes",
    "clothes pin",
    "coffee mug",
    "coffee pot",
    "comb",
    "comic book",
    "computer",
    "conditioner",
    "container of pudding",
    "cookie jar",
    "cookie tin",
    "cork",
    "couch",
    "cow",
    "cowboy hat",
    "craft book",
    "credit card",
    "crow",
    "crowbar",
    "cucumber",
    "cup",
    "dagger",
    "deodorant",
    "desk",
    "dictionary",
    "dog",
    "dolphin",
    "domino set",
    "door",
    "dove",
    "drawer",
    "drill press",
    "egg",
    "egg beater",
    "egg timer",
    "empty bottle",
    "empty jar",
    "empty tin can",
    "eraser",
    "extension cord",
    "eye liner",
    "face wash",
    "fake flowers",
    "feather",
    "feather duster",
    "few batteries",
    "fish",
    "fishing hook",
    "flag",
    "flashlight",
    "floor",
    "flowers",
    "flyswatter",
    "food",
    "football",
    "fork",
    "fridge",
    "frying pan",
    "game CD",
    "game cartridge",
    "garden spade",
    "giraffe",
    "glass",
    "glasses",
    "glow stick",
    "grid paper",
    "grocery list",
    "hair brush",
    "hair clip",
    "hair pin",
    "hair ribbon",
    "hair tie",
    "hammer",
    "hamster",
    "hand bag",
    "hand fan",
    "hand mirror",
    "handbasket",
    "handful of change",
    "handheld game system",
    "hanger",
    "harmonica",
    "helmet",
    "house",
    "ice cream stick",
    "ice cube",
    "ice pick",
    "incense holder",
    "ipod",
    "ipod charger",
    "jar of jam",
    "jar of peanut butter",
    "jar of pickles",
    "jigsaw puzzle",
    "key",
    "key chain",
    "keyboard",
    "keychain",
    "keys",
    "kitchen knife",
    "knife",
    "lace",
    "ladle",
    "lamp",
    "lamp shade",
    "laser pointer",
    "leg warmers",
    "lemon",
    "letter opener",
    "light",
    "light bulb",
    "lighter",
    "lime",
    "lion",
    "lip gloss",
    "locket",
    "lotion",
    "magazine",
    "magnet",
    "magnifying glass",
    "map",
    "marble",
    "martini glass",
    "matchbook",
    "microphone",
    "milk",
    "miniature portrait",
    "mirror",
    "mobile phone",
    "model car",
    "money",
    "monitor",
    "mop",
    "mouse pad",
    "mp3 player",
    "multitool",
    "music CD",
    "nail",
    "nail clippers",
    "nail filer",
    "necktie",
    "needle",
    "notebook",
    "notepad",
    "novel",
    "ocarina",
    "orange",
    "outlet",
    "pack of cards",
    "package of crisp and crunchy edibles",
    "package of glitter",
    "packet of seeds",
    "pail",
    "paint brush",
    "paintbrush",
    "pair of binoculars",
    "pair of dice",
    "pair of earrings",
    "pair of glasses",
    "pair of handcuffs",
    "pair of knitting needles",
    "pair of rubber gloves",
    "pair of safety goggles",
    "pair of scissors",
    "pair of socks",
    "pair of sunglasses",
    "pair of tongs",
    "pair of water goggles",
    "panda",
    "pants",
    "paper",
    "paperclip",
    "pasta strainer",
    "pearl necklace",
    "pen",
    "pencil",
    "pencil holder",
    "pepper shaker",
    "perfume",
    "phone",
    "photo album",
    "picture frame",
    "piece of gum",
    "pillow",
    "pinecone",
    "plastic fork",
    "plate",
    "plush bear",
    "plush cat",
    "plush dinosaur",
    "plush dog",
    "plush frog",
    "plush octopus",
    "plush pony",
    "plush rabbit",
    "plush unicorn",
    "pocketknife",
    "pocketwatch",
    "pool stick",
    "pop can",
    "postage stamp",
    "puddle",
    "purse",
    "purse/bag",
    "quartz crystal",
    "quilt",
    "rabbit",
    "radio",
    "rat",
    "remote",
    "rhino",
    "ring",
    "rock",
    "roll of duct tape",
    "roll of gauze",
    "roll of masking tape",
    "roll of stickers",
    "roll of toilet paper",
    "rolling pin",
    "rope",
    "rubber band",
    "rubber duck",
    "rubber stamp",
    "rug",
    "rusty nail",
    "safety pin",
    "sailboat",
    "salt shaker",
    "sand paper",
    "sandal",
    "sandglass",
    "scallop shell",
    "scarf",
    "scotch tape",
    "screw",
    "screwdriver",
    "seat belt",
    "shampoo",
    "shark",
    "sharpie",
    "shawl",
    "sheep",
    "sheet of paper",
    "shirt",
    "shirt button",
    "shoe lace",
    "shoes",
    "shopping bag",
    "shovel",
    "sidewalk",
    "sketch pad",
    "slipper",
    "small pouch",
    "snail shell",
    "snowglobe",
    "soap",
    "soccer ball",
    "socks",
    "sofa",
    "spatula",
    "speakers",
    "spectacles",
    "spice bottle",
    "sponge",
    "spool of ribbon",
    "spool of string",
    "spool of thread",
    "spool of wire",
    "spoon",
    "spring",
    "squirrel",
    "squirt gun",
    "statuette",
    "steak knife",
    "stick",
    "stick of incense",
    "sticker book",
    "sticky note",
    "stockings",
    "stop sign",
    "straw",
    "street lights",
    "sun glasses",
    "sword",
    "table",
    "tea cup",
    "tea pot",
    "teddies",
    "television",
    "tennis ball",
    "tennis racket",
    "thermometer",
    "thimble",
    "thread",
    "tiger",
    "tire swing",
    "tissue box",
    "toe ring",
    "toilet",
    "toilet paper tube",
    "tomato",
    "tooth pick",
    "toothbrush",
    "toothpaste",
    "toothpick",
    "towel",
    "toy boat",
    "toy car",
    "toy plane",
    "toy robot",
    "toy soldier",
    "toy top",
    "trash bag",
    "tree",
    "trucks",
    "tube of lip balm",
    "tube of lipstick",
    "turtle",
    "tv",
    "tweezers",
    "twister",
    "umbrella",
    "vase",
    "video games",
    "wallet",
    "washcloth",
    "washing machine",
    "watch",
    "water",
    "water bottle",
    "wedding ring",
    "whale",
    "whip",
    "whistle",
    "white out",
    "window",
    "wine glass",
    "wireless control",
    "wishbone",
    "wooden spoon",
    "word search",
    "wrench",
    "wristwatch",
    "zebra",
    "zipper"
  ],
  "ergative_verbs": [
        "accelerate",
        "acclimatize",
        "acculturate",
        "acidify",
        "activate",
        "align",
        "asphyxiate",
        "attach",
        "awaken",
        "bake",
        "bend",
        "bifurcate",
        "blacken",
        "bleed",
        "boast",
        "boil",
        "bounce",
        "break",
        "brighten",
        "broaden",
        "bruise",
        "burn",
        "burst",
        "bust",
        "change",
        "char",
        "choke",
        "clarify",
        "clear",
        "clink",
        "clog",
        "close",
        "collapse",
        "combine",
        "compile",
        "connect",
        "contort",
        "cook",
        "corrode",
        "count",
        "crack",
        "crash",
        "crumble",
        "crumple",
        "crystallize",
        "dampen",
        "darken",
        "deactivate",
        "deaden",
        "decelerate",
        "decrease",
        "deepen",
        "deflate",
        "deform",
        "dent",
        "deploy",
        "derail",
        "despawn",
        "deteriorate",
        "detonate",
        "dilate",
        "dim",
        "distill",
        "distort",
        "dock",
        "download",
        "drag",
        "drain",
        "drill",
        "drive",
        "drop",
        "drown",
        "dry",
        "duplicate",
        "eat",
        "eject",
        "empty",
        "end",
        "entwine",
        "erase",
        "erode",
        "escalate",
        "expand",
        "exsanguinate",
        "factor",
        "fail",
        "fatten",
        "fill",
        "fire",
        "flash",
        "flatten",
        "flip",
        "float",
        "flood",
        "flunk",
        "flush",
        "fly",
        "fold",
        "fracture",
        "freeze",
        "freshen",
        "fry",
        "gather",
        "glide",
        "graduate",
        "grieve",
        "grow",
        "halt",
        "halve",
        "hang",
        "harden",
        "harmonize",
        "hasten",
        "heal",
        "honk",
        "hurt",
        "hush",
        "ignite",
        "improve",
        "increase",
        "inflame",
        "inflate",
        "ionize",
        "jam",
        "land",
        "launch",
        "lean",
        "lengthen",
        "lessen",
        "lighten",
        "liquify",
        "lock",
        "loosen",
        "lower",
        "madden",
        "march",
        "melt",
        "mend",
        "merge",
        "mix",
        "moisten",
        "move",
        "open",
        "operate",
        "orientate",
        "overtire",
        "overtrain",
        "overwork",
        "park",
        "pass",
        "play",
        "plunge",
        "pop",
        "quicken",
        "quiet",
        "quieten",
        "radiate",
        "raise",
        "rattle",
        "reboot",
        "redden",
        "regrow",
        "rejuvenate",
        "reload",
        "relocate",
        "rest",
        "resuscitate",
        "reverse",
        "revert",
        "revive",
        "rewind",
        "ripen",
        "roast",
        "rock",
        "roll",
        "rotate",
        "rouse",
        "run",
        "rupture",
        "rush",
        "rustle",
        "sadden",
        "sail",
        "scatter",
        "scorch",
        "scramble",
        "scroll",
        "sell",
        "separate",
        "shake",
        "shatter",
        "shift",
        "shine",
        "shorten",
        "shrink",
        "shut",
        "sicken",
        "simplify",
        "sink",
        "skip",
        "slam",
        "slant",
        "slide",
        "slow",
        "smash",
        "smear",
        "soak",
        "soften",
        "spawn",
        "spill",
        "spin",
        "splash",
        "splatter",
        "splinter",
        "split",
        "start",
        "starve",
        "steer",
        "stew",
        "stick",
        "stiffen",
        "stir",
        "stop",
        "straighten",
        "strangle",
        "strengthen",
        "stretch",
        "suffocate",
        "sway",
        "sweep",
        "sweeten",
        "swing",
        "tangle",
        "tauten",
        "tear",
        "teleport",
        "terminate",
        "thaw",
        "thicken",
        "thrill",
        "tighten",
        "tip",
        "tire",
        "toast",
        "toll",
        "toot",
        "topple",
        "toughen",
        "train",
        "transfer",
        "transform",
        "turn",
        "twist",
        "twitch",
        "unbend",
        "unbutton",
        "unclog",
        "uncrumple",
        "unfasten",
        "unfurl",
        "unload",
        "unlock",
        "unravel",
        "unroll",
        "untangle",
        "untwist",
        "unwind",
        "unzip",
        "upload",
        "vaporize",
        "waft",
        "wake",
        "weaken",
        "weary",
        "whiten",
        "widen",
        "wilt",
        "wind",
        "worry",
        "worsen"
    ]
};

const generate = () => {

    // Begin with the two primary nouns -- our "Lasers" and "Feelings"
    var nouns = words['nouns'];

    var i = Math.floor(Math.random()*nouns.length);
    var noun1 = nouns[i];
    if(noun1.match(/[y]$/i)) {
      noun1 = noun1.replace(/[y]$/i,'ies');
    } else if (noun1.match(/[^i][aeiou]{1,2}[xs]$/i)) {
      noun1 += 'es';
    } else if (!noun1.match(/ce$/i) && !noun1.match(/s$/i)) {
      noun1 += 's';
    }
    $(".noun1").text(noun1);
    nouns.splice(i,1);

    var i = Math.floor(Math.random()*nouns.length);
    var noun2 = nouns[i];
    if(noun2.match(/[y]$/i)) {
      noun2 = noun2.replace(/[y]$/i,'ies');
    } else if (noun2.match(/[^i][aeiou]{1,2}[xs]$/i)) {
      noun2 += 'es';
    } else if (!noun2.match(/ce$/i)) {
      noun2 += 's';
    }
    $(".noun2").text(noun2);
    nouns.splice(i,1);

    // Player styles
    var adjs = words['adjs'];
    var styles = "";
    for (var i = 0; i < 5; i++) {
      var a = Math.floor(Math.random()*adjs.length);
      styles += `<b class='text-capitalize'>${adjs[a]},</b> `;
      adjs.splice(a,1);
    }
    var a = Math.floor(Math.random()*adjs.length);
    styles += `or <b class='text-capitalize'>${adjs[a]}.</b>`;
    $(".player-styles").html(styles);

    // Player roles
    var occupations = words['occupations'];
    var roles = "";
    for (var i = 0; i < 5; i++) {
      var o = Math.floor(Math.random()*occupations.length);
      roles += `<b class='text-capitalize'>${occupations[o]},</b> `;
      occupations.splice(o,1);
    }
    var o = Math.floor(Math.random()*occupations.length);
    roles += `or <b class='text-capitalize'>${occupations[o]}.</b>`;
    $(".player-roles").html(roles);

    // Game Setting
    var categories = words['categories'];
    var setting = categories[Math.floor(Math.random()*categories.length)];
    $('.game-setting').text(setting);

    // Player inventory
    var objects = words['objects'];
    var inventory = "";
    for (var i = 0; i < 2; i++) {
      var o = Math.floor(Math.random()*objects.length);
      var a = objects[o].match(/^[aeiou]/i) ? 'an' : 'a';
      inventory += `${a} ${objects[o]}, `;
      objects.splice(o,1);
    }
    var o = Math.floor(Math.random()*objects.length);
    var a = objects[o].match(/^[aeiou]/i) ? 'an' : 'a';
    inventory += `and ${a} ${objects[o]}.`;
    $(".player-inventory").html(inventory);

    // Character goals
    var ergative_verbs = words['ergative_verbs'];
    var goals = "";
    for (var i = 0; i < 5; i++) {
      var e = Math.floor(Math.random()*ergative_verbs.length);
      var s = Math.floor(Math.random()*3);
      var n = Math.floor(Math.random()*nouns.length);
      var noun = nouns[n];
      var a = ``;
      var p = ``;
      var pl = ``;
      if (s == 1) {
        a = ` the`;
      } else if (s == 2) {
        a = noun.match(/^[aeiou]/i) ? ' an' : ' a';
      } else {
        if(noun.match(/[y]$/i)) {
          noun = noun.replace(/[y]$/i,'ies');
        } else if (noun.match(/[^i][aeiou]{1,2}[xs]$/i)) {
          pl = 'es';
        } else if (!noun.match(/ce$/i)) {
          pl = 's';
        }
      }
      goals += `<b class='text-capitalize'>${ergative_verbs[e]}</b><b>${a}</b> <b class='text-capitalize'>${noun}${pl}</b>,</b> `;
      nouns.splice(n,1);
      occupations.splice(o,1);
    }
    $(".character-goals").html(goals);

    // Party name
    var occupations = words['occupations'];
    var party = occupations[Math.floor(Math.random()*occupations.length)];
    if(party.match(/[y]$/i)) {
      party = party.replace(/[y]$/i,'ies');
    } else if (party.match(/[^i][aeiou]{1,2}[xs]$/i)) {
      party += 'es';
    } else if (!party.match(/ce$/i)) {
      party += 's';
    }
    $(".party-name").text(party);
}

$(document).ready(() => {
  generate();
});
